services:
  #  authfreeaskinternet:
  #    image: authfreeaskinternet
  #    build: .
  #    ports:
  #      - "3001:3001"
  #    extra_hosts:
  #      - "host.docker.internal:host-gateway"
  iopaint:
    container_name: iopaint
    build: 
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./.cache:/app/.cache
      - ./venv:/app/opt/venv
    ports:
      - "3000:3000"
        #extra_hosts:
        #  - "host.docker.internal:host-gateway"
