services:
  iopaint:
    container_name: iopaint-wrapper
    volumes:
      - ./.cache:/root/.cache
      - ./venv:/opt/venv
    build: 
      dockerfile: Dockerfile
      context: .
    ports:
      - "3000:3000"
      - "8080:8080"
        #extra_hosts:
        #  - "host.docker.internal:host-gateway"
volumes:
    venv:
