services:
  iopaint-wrapper:
    container_name: iopaint-wrapper
    volumes:
      - ./.cache:/app/.cache
      - ./venv:/app/venv
    environment:
      - VIRTUAL_ENV=/app/venv
    build: 
      dockerfile: Dockerfile
      context: .
    ports:
      - "3000:3000"
      - "8080:8080"
        #extra_hosts:
        #  - "host.docker.internal:host-gateway"
volumes:
    venv:
