services:
  iopaint-wrapper:
    container_name: iopaint-wrapper
    #volumes:
    #  - ./.cache:/root/.cache
    #  - ./venv:/app/venv
    environment:
      - VIRTUAL_ENV=/app/venv
    build: 
      dockerfile: Dockerfile
      context: .
    ports:
      - "3100:3000"
      - "8080:8080"
      - "9880:9880"
        #extra_hosts:
        #  - "host.docker.internal:host-gateway"
volumes:
    venv:
